# config.yml
alpaca:
  API_KEY: ALPACA_API_KEY
  API_SECRET: ALPACA_API_SECRET
  BASE_URL: "https://paper-api.alpaca.markets/v2"
  PAPER: true

Backtest: true
DataProvider: YahooDataBacktesting
StartDate: 2019-10-01
EndDate: 2024-12-31
Symbols:
  - SPY
  - AAPL
  - MSFT
InitialCash: 100000
